services:
    postgres:
        image: postgres:latest
        container_name: postgres_db
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: password
            POSTGRES_DB: mydb
        ports:
            - "5431:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata: